name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build executable for release
        run: swift build -c release --product trash
      - name: Compress archive
        run: tar -czf trash_${{ github.ref_name }}_arm64-apple-macosx.tar.gz -C .build/arm64-apple-macosx/release trash
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: trash_${{ github.ref_name }}_arm64-apple-macosx.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
